### ISSUE TITLE
Endless Sky Permanent Website

### ISSUE THREAD

**Issue by kikotheexile** [endless-sky/endless-sky.github.io#3]
I'm a steam noob, so if there is a better way for me to get in touch with MZ please let me know. 

I wanted to let you know that a few of us on Steam have taken the liberty of coming up with temporary solutions to a centralized mod-hosting plan, and we have also been looking for more permanent solutions. 

On the front of the permanent plan, I am currently in negotiations with a possible web host for an unrelated project, but am more than willing to set up, pay for, and provide centralized, dedicated Endless Sky website though this host, as I can get a good deal on it. 

I am not requesting any kind of help for this, nor payment. I am only looking for permission and direction. We would start with 10gb free storage space for mod hosting, and once we reached that cap I would have the option to buy more. The main page and forums would most likely be mobile friendly as well as launcher friendly (I am also working on a few game launcher designs) 

I just need to get an OK from MZ, and a list of any features you would like added to the website. 

If you have any questions or comments  the best way to contact me is via steam, but I will also be keeping an eye on this issue.

**Comment by endless-sky** [comment]
An alternative for now would just be to use the [current website](http://endless-sky.github.io/) hosted on github. If a page were added as an index of mods, people could submit mods in the form of pull requests. The only disadvantages I can see to hosting on GitHub are:

* No custom domain name.
* Anyone who wants to upload a mod would need to sign up for a GitHub account.

The biggest advantage would be to avoid having the game content spread out across yet another web platform that has to be maintained separate from the others.

**Comment by kikotheexile** [comment]
This idea is to take care of the issue on the roadmap.

> Plugins:

    Centralized website for all available plugins.


Custom domain, news, and a centralized website/forum that the google group, github users, and steam users can all use to share their plugins. 

If you would rather continue using github, google, and steam independently, I won't complain. This would be, however, a true endless sky website. 

It's your call at the end of the day, but I am willing to get it set up, and am willing to pay the hosting charges.

**Comment by kikotheexile** [comment]
Basically I just need a solid "yea, sure, do it, or whatever." or a "yea, no, nows not the time but thanks anyway." before I can move forward in the negotiations and get it set up, so I don't end up wasting anyone's time.

**Comment by evan153** [comment]
@endless-sky 
I started the alternative you suggested already lol: 
https://evan153.github.io/ES-Mod-Share/
https://github.com/evan153/ES-Mod-Share

Kiko wanted to scale it up based on several ideas, partnering with a few other Endless Sky content creators, and wants approval from MZ the main dude. :sunglasses:

**Comment by kikotheexile** [comment]
I'm literally just going through the roadmap and being like, "Yea, I can do this, and I can do this, so why don't I?" 

A plugins website, in my case, is cheap and easy. I have access to markets and companies closed to the vast majority of consumers, and can get excellent deals on hosting. In fact, most hosts won't even negotiate price and function, my hosts will. I'm not asking for exclusive rights to the IP or whatever, just approval to actually make it a reality, working under the assumption that since it's on the roadmap, its a wanted feature. 

I just don't want to pay out of pocket and annoy possible partners for something that isn't actually wanted, hence why I asked rather than just did. Lol. 

Like I said, its your call, I'm chill either way. Do you want a custom domain full website for this game, which includes centralized mod hosting and can be viewed in launchers without being ugly AF, or would you rather stick with github? The former is free for you, the latter is free for me. So I'll be happy either way. 

Also, I am sorry if i come across as snarky or anything. I have barely slept in the past three days, and im starting to get a bit old for all-nighters.

**Comment by endless-sky** [comment]
@kikotheexile, for now I'd prefer to stay with GitHub, just to keep things simple and avoid having the project spread across even more web locations.

@evan153, I'm glad your HTML / Javascript knowledge is more up to date than mine. I haven't done real website design in about 16 years, and I never would have even realized those animated pop-ups, etc. could all be done with scripting. Very cool. A few suggestions I'd make:

1. Standardizing the cover image size, or at least its aspect ratio (16:9 would be best).
2. Adding support for scrolling through a whole set of images for each mod (i.e. a screenshot gallery) in the pop-up panel.
3. The gallery should include some descriptive text for each plugin. Maybe something like:

![tile](https://cloud.githubusercontent.com/assets/11450262/18016496/aa871688-6b9a-11e6-81cb-9d6f38f34448.png)

(Not saying you should use that exact font, layout, etc. - I'm only suggesting what pieces of information should probably be included in each tile.)

**Comment by kikotheexile** [comment]
As you say, and thank you for the speedy reply, 

I'll drop this from negotiation and revise the launcher designs to be more compatible with github. Unfortunately this removes the central repository aspect and news feed simply - unless Evan's idea unifies all the separate modding groups. Which, as it does seem straight forward enough, it should. 

Creates a negligible about of extra work for me, and we should still be able to knock out a huge chunk of the roadmap so long as we continue collaboration. I'll update the steam community accordingly.

**Comment by evan153** [comment]
@endless-sky Yeah, that web page definitely needs some work. It was just made quickly to be an example of how we could make a mod sharing website on Github. Thanks for the suggestions. I will work on it some more now that I know you want to stay on Github. :smile:

**Comment by endless-sky** [comment]
The GitHub web page hosting system also has support for blogs / news articles. I just have not had time to look into exactly how that is done.

**Comment by kikotheexile** [comment]
I'm a github noob, and have not seen all that this site supports.

If this can be made launcher friendly, and if there is a way to direct import files the easy way, then the majority of the plugins roadmap may be completed by the end of September - probably sooner.

**Comment by evan153** [comment]
Maybe [Jekyll](https://jekyllrb.com/) but afaik Github only supports static sites. Importing files would probably depend more on how you code the launcher.
Where is this roadmap located btw?

**Comment by LocalGod79** [comment]
on the wiki:
https://github.com/endless-sky/endless-sky/wiki/DevelopmentRoadmap

**Comment by kikotheexile** [comment]
https://github.com/endless-sky/endless-sky/wiki/DevelopmentRoadmap

And the launcher import and movement would depend heavily upon how I code it, but the biggest deal is i need uncompressed complete files in order to make things as easy as humanly possible on the human/player side of things. 

I will be making custom launchers for differnet user groups, but the steam one will be as streamlined and straight forward as possible, and make it easiest on the player to find, edit, and set load order of plugins.

**Comment by kikotheexile** [comment]
Eh, i just realized that - out of context - that last post makes me look something like a moron. I'm sure you all know exactly where I'm coming from on this front though, and its easy enough to get around (generally speaking) 

Point is i just don't know exactly how Github likes to do things, and thus idk how to make the launcher compatible with that. That's beside the point, im sure it won't be complicated at all.

**Comment by KevinKorzekwa** [comment]
Github pages definitely support jekyll, @evan153.  My understanding is that there is not really a limitation on the types of things you can do with github pages, it is really just the scale.  If this project ever gets large enough to exceed the bandwidth and storage limits set by github, then it would need to be moved to a different hosting provider.  

Until then, the sky's endless, you can give it a custom domain name, code a super fancy website, do whatever.  Start out here, it's great. [pages.github.com](https://pages.github.com/) and [github pages basics](https://help.github.com/categories/github-pages-basics/)

**Comment by evan153** [comment]
@KevinKorzekwa I said Jekyll because maybe that's what endless-sky was talking about for blogs / news. There definitely is a limit. I wasn't saying that Github supports static sites only as an opinion lol. Have you looked at the site I already made and linked earlier? That's about all we'd be able to do. (well we can style it and clean it up too)

Github isn't a web hosting provider. It's for projects / collaboration. The only languages we could use for pages would be HTML/CSS/JS and some frameworks / libraries. This means we can't use: Node, Python, Ruby, PHP, or any other server side languages, and we can't have dynamic pages.

**Comment by KevinKorzekwa** [comment]
Thanks for the correction, I misunderstood.  I was trying to say that there's a lot we can do with a static site, and I think we could make a good repository within that limit.

**Comment by endless-sky** [comment]
I already cross-posted this to Evan's new website repository, but I'd be interested in everyone's feedback on this as a possible new visual design for the website:

http://endless-sky.github.io/new/

My goal was to keep the same minimal style and "design language" as the game, but to adapt it to website form. It's only a single page (links don't work), and the HTML / CSS is not great, so I'm just interested in feedback on the visuals and the alternative introduction material. (In the end, I think using Jekyll to generate pages would be much more maintainable than plain HTML like this.)

**Comment by comnom** [comment]
So I've been playing around trying learn some HTML and CSS, and I focused on making a plugin page since it's easier to work within something rather than making it from scratch. The surprising (to me anyway) thing is that it's functional. It takes several ideas from the proof of concept site, but marries them to the style of the rest of the site.

Plugin's are a collection, just like screenshots, and the gallery view includes all the immediately relevant bits.

```
---
title: Eternals
author: <a href="https://github.com/comnom">comnom</a>
cover: /images/plugins/eternals/cover.jpg
screenshots:
 - /images/plugins/eternals/ss_combat.jpg
 - /images/plugins/eternals/ss_homeworld.jpg
 - /images/plugins/eternals/ss_outfitter.jpg
blurb: Some short description for the gallery view.
description: Some longer description for the lightbox caption.
website: https://comnom.github.io/Eternals/
release: https://github.com/comnom/Eternals/releases/latest/
tags:
 - ships
 - outfits
 - systems
 - aliens
---
```
![site0](https://cloud.githubusercontent.com/assets/22107649/21121205/16f03644-c099-11e6-8a6f-8048203f1da0.jpg)

The lightbox from the screenshot gallery gets repurposed to display a larger cover image, and any number of screenshots that get cycled through on a per mod basis. The caption gets switched to a long form description, with download and homepage links. A close button is added as well, since a slight mis-click would have the lightbox close otherwise (I tried to match the style of the arrows, but man did I find Inkscape obtuse). This is all added as separate css/js to leave the screenshot gallery lightbox untouched.

![site1](https://cloud.githubusercontent.com/assets/22107649/21121229/2ca1c5b6-c099-11e6-9388-b06cb3d41b64.jpg)

It's fairly plain, and the code's probably messy, but I figured since it works I'd share, maybe if you dig part of it it'd save you some work. I can add the files I used for testing and grabbing the screenshots if you'd like to build a filled out local copy from the fork. If not that's cool, it's really just a learning exercise for me. The fork is here if you're curious: https://github.com/comnom/endless-sky.github.io

**Comment by CodeDraken** [comment]
I second the idea that an official plugin site should be merged onto the main ES website. I recently changed my name and that broke any links going to evan153.github... This is the link for proof of concept now: https://codedraken.github.io/ES-Mod-Share/

It would be more inviting for contributors, better UX for players because they can find plugins on the same site, and I can change my name without it breaking :stuck_out_tongue_closed_eyes:

**Comment by quyykk** [comment]
I think this can be closed now. This site can host plugins since a good while.
