### ISSUE TITLE
More detailed build instructions for Windows.

### ISSUE THREAD

**Issue by retrue** [endless-sky/endless-sky.github.io#4]
I tried to compile the code following the instructions on the Build section of the Wiki.
After installing and strugling blindly with the options (complete n00b here) I was able to compile the code getting zero error messages and zero warnings. After adding the dlls from a release version to the directory of the game, when I tried to launch it, I got a weird message. Something about linking.
More detailed instructions or a tutorial would be welcome.
I can compile the code using Linux Mint, but I usually play from Windows. I barely use Mint at the moment.
EDIT: Dunno what I did, but I have downloaded everything again, compiled, added the missing dlls, and the game runs now. Still, I think a more complete information or a tutorial are important.

**Comment by Bladewood** [comment]
This is probably how it works (probably not):

1. Install mingw-w64 from the link on the build page.
2. Scroll down to "mingw32-gcc-g++" and check the box next to it. (should try checking the one that says "bin", because that'll check "dev" too, I'm not sure which one is actually required)
3. Click on "Installation", then "Apply Changes".
4. Open the provided zip file that contains "a full set of development libraries". Put the folder in there in C:\. Alternatively, as the page says, you can put the libraries somewhere else, and open the CodeBlocks project file in notepad editor or something, scroll down to all of those "<Add library="..." />" lines, then change the paths accordingly.
5. Find a source build of Endless Sky and open the provided cbp file. If necessary, click on that little button (should say "Debug", if you are a first-time compiler) that when clicked will list "Debug", "Release", and "Win32", and click on the version that corresponds to your computer. Then click on "build" on the top row and then "build" in the drop-down menu.
6. Wait a few minutes while Endless Sky compiles.
7. Go to the now generated "bin" folder, click on the folder inside, and move EndlessSky.exe to where all the rest of the game files are located.
8. Look in your development libraries zip file. Click on "dev64", then "bin", then move everything in that folder to the game directory.
9. Click on EndlessSky.exe to start the game.

You will probably come up with errors and the like by using this guide, and even if you don't, I'm sure it can be reworded to be easier to follow.

**Comment by retrue** [comment]
Yeah, I figured out all of that myself. Right now, in 5 minutes, I download the code, compile and launch the game, but the first time was hard.
I tried to compile the game in Linux Mageia 5 but I was not able. I got to install all the libraries, but I guess they weren't the correct versions, and the compilation stopped with errors. Mageia is a rpm distro, based on Mandrake, that was based on RedHat.

**Comment by Bladewood** [comment]
Yes, it took months for me to figure out to compile the game for the first time.

**Comment by SirStigII** [comment]
> Building to ensure sources are up-to-date
> Selecting target: 
> Debug
> Adding source dir: C:\endless-sky-master\
> Adding source dir: C:\endless-sky-master\
> Adding file: C:\endless-sky-master\bin\Debug\EndlessSky.exe
> Changing directory to: C:/endless-sky-master/.
> Set variable: PATH=.;C:\dev64\lib;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Users\joshw\AppData\Local\Microsoft\WindowsApps;
> Starting debugger: C:\Program Files\mingw-w64\x86_64-6.3.0-posix-sjlj-rt_v5-rev2\mingw64\bin\gdb.exe -nx -fullname  -quiet  -args C:/endless-sky-master/bin/Debug/EndlessSky.exe
> done
> Registered new type: wxString
> Registered new type: STL String
> Registered new type: STL Vector
> Setting breakpoints
> Debugger name and version: GNU gdb (GDB) 7.11.1
> Starting the debuggee failed: No executable specified, use `target exec'.
> Debugger finished with status 0

I'm getting this when I try and debug
